### ISSUE TITLE
b_specific_example_1

### ISSUE THREAD

**Issue by rebeccajohnson88** [ilundberg/replication#4]
Commit [here](https://github.com/rebeccajohnson88/replication/commit/a068eaaea54e4541cc8af51e282d3a9cb80fc80b)

Looks good! Only small question/possible change (changed in above commit and it produces nearly identical results but with some small diff in ~4th sig dig of p value is:

- Initial code:

Does the filtering out of irrelevant cohorts restriction, then adjusts weights per mgcv doc to divide weight by mean, then does further analytic restriction to remove those missing any of relevant covars

```
filter(cohort >= (1972 - 25) & cohort <= (2018 - 34)) %>%
  mutate(num_inCohortRange = n(),
         weight = weight / mean(weight)) %>%
  # Note the sample size with missing dropped
  filter(!is.na(college) & !is.na(cohort) & !is.na(father_category) & 
           !is.na(mother_category) & !is.na(Gender) &
           !is.na(weight))
```

It seems like the weights adjustment might be better to do after all sample restrictions so in updated code just changed order of that step to be after the second-round filters, but not positive that's correct

```
d <- d_init %>% filter(is_focal_cohort & is_observed_all) %>%
  mutate(weight = weight/mean(weight))
```

**Comment by ilundberg** [comment]
Great. I updated my repository to bring in your changes in and then made a few tiny aesthetic changes in [this commit](https://github.com/ilundberg/replication/commit/fe7a94a724c1c87f65a5d6642562a00d8343090d#).

Then I ran the code and updated BuchmannDiPrete_output.txt and gss_fourPanel.pdf in Overleaf.
